### ISSUE TITLE
Migration zip missing

### ISSUE THREAD

**Issue by leftshift** [lineageos4microg/docker-lineage-cicd#105]
The links for the migration zip from the website to https://download.lineage.microg.org/extra currently lead to a 404.

This was probably something that went missing with the move to LineageOS 16, but makes it impossible to migrate right now.

**Comment by ashimokawa** [comment]
I found something on my disc. 

You can also extract the shell script and see what it does, push is to your device in recovery, and execute it instead of flashing the zip. 

**USE AT YOUR OWN RISK I CANNOT SAY IF IT STILL WORKS** 


[lineageos-for-microg-keys-migration.zip](https://github.com/lineageos4microg/docker-lineage-cicd/files/5204681/lineageos-for-microg-keys-migration.zip)

**Comment by spolack** [comment]
I reprovided the original migration zip. Please report back whether its still working with lineageos 17.1, as i personally dont use it.

**Comment by kurt-by** [comment]
@spolack confirmed with jacticelte 17.1 unencrypted with magisk and lineageOS recovery.
I get an error message about a missing xms file, but lineage 4 microG installs without a problem. Automatic magisk restore was successful.

**Comment by leftshift** [comment]
Thanks, worked for me with lavender and file based encryption.

**Comment by cholin** [comment]
I'm sorry but I can not confirm what the others are saying: For my Pixel 3A (sargo) the migration.zip fails for a fresh Lineage 17.1 (20200908 and as well 20200922). This was as well already noticed by @kurt-by: `package.xml not found`

```
$ adb sideload lineageos-for-microg-keys-migration.zip

[Device Output]
Finding update package...
Opening update package...
Verifying update package...
E:failed to verify whole-file signature
Update package verification took 0.2 s (result 1).
E: Signature verification failed
E:error: 21
[manual confirmation]
Finding update package...
Opening update package...
Installing update...
ERROR: package.xml not found. Exiting...
```

Not surprisingly the sideload then for lineage-17.1-microG fails later on:

```
$ adb sideload lineage-17.1-20200924-microG-sargo.zip

[Device Output]
Finding update package...
Opening update package...
Verifying update package...
E:failed to verify whole-file signature
Update package verification took 41.1 s (result 1).
E: Signature verification failed
E:error: 21
[manual confirmation]
Finding update package...
Opening update package...
Installing update...
Step 1/2
Error applying update: 26 (ErrorCode:kDownloadMetadataSignatureMismatch)
E:Error in /sideload/package.zip (status 1)
```

Am I missing here something or does the migration just don't work for 17.1 anymore with certain devices like the Pixel 3A? Is there another way of installing it like for instance a certain lineage-17.1-microg recovery image (which already contains the correct keys)?

**Comment by cholin** [comment]
I'm not that familiar with Android but looking into the source I managed to finally flash linage-microg on my Pixel3A. I had to use the lineage recovery as the Pixel3A uses ab partitions. Generally you need to replace key material in order to get the update working:

1. Flash official linage recovery
```
$ adb reboot bootloader
$ fastboot flash boot lineage-17.1-[BUILD]-recovery-[DEVICE].img
```

2. Boot into recovery and do the following

* Factory reset (Factory Reset -> Format data)
* enable ADB (Advanced -> Enable ADB)

3. Get and extract lineage-microg public key 

```
$ wget https://download.lineage.microg.org/extra/lineageos-for-microg-keys-migration.zip
$ unzip -p lineageos-for-microg-keys-migration.zip META-INF/com/google/android/update-binary > update-binary
$ cat <<EOF > update-payload-key.pub.pem
-----BEGIN PUBLIC KEY-----
$(grep release_key= update-binary | cut -d '"' -f 2 | fold -w 64)
-----END PUBLIC KEY-----
EOF
```

4. Push correct public key to device

```
$ adb push update-payload-key.pub.pem /system/etc/update_engine/
```

If you want to fix the manual prompt for signature verification, you have to provide your own `otacerts.zip`:

1. Download linage-microg zip for your device and extract cert

```
$ unzip -p lineage-17.1-[BUILD]-microG-[DEVICE].zip META-INF/com/android/otacert > cert.x509.pem
```

2. Pull and extract otacerts from device

```
$ adb pull etc/security/otacerts.zip
$ mkdir otacerts && cd otacerts
$ unzip ../otacerts.zip
```

3. Replace certs and bundle again
```
$ cp ../cert.x509.pem vendor/lineage/build/target/product/security/lineage.x509.pem
$ cp ../cert.x509.pem lineage/signing/signing-keys/releasekey.x509.pem
$ zip -r otacerts.zip .
$ adb push otacerts.zip /system/etc/security/
$ cd ..
```

After this you can apply the update without issues:

1. Enable sideload (Apply update -> Apply from ADB)
2. Push the lineage-microG: `$ adb sideload lineage-17.1-[BUILD]-microG-[DEVICE].zip`
3. Reboot and be happy

**Comment by kurt-by** [comment]
@cholin Thank you for that procedure.
@spolack do you think this is mandatory for all a/b devices? If yes, and taking into account, half of the migration candidates have GApps installed. I would say: Dont't try migration on an a/b device, and clean flash lineage4microG instead.
@cholin could you please help out with a procedure for removing GApps in a clean flash? Here we have one not able to get rid of play store app https://forum.xda-developers.com/showpost.php?p=83600943&postcount=1989

**Comment by eode** [comment]
@cholin @spolack This procedure worked for Bonito / Pixel 3a XL where nothing else did.  Thank you.

Is there somewhere appropriate that this can be documented?  It was.. ..painful to find.
