### ISSUE TITLE
bacon microG recovery broken 

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/docker-lineage-cicd#143]
$ fastboot flash recovery lineage-17.1-20210114-recovery-bacon.img
works as expected. Power and volume down boots into lineageOS recovery
$ fastboot flash recovery lineage-17.1-20210115-microG-bacon-recovery.img
Shows no error messages. But Power and volume down boots into previously installed lineage4microg.
In lineage4microg built in updater seems to work but taping "INSTALL" and "OK" reboots into system without applying update

**Comment by JuniorJPDJ** [comment]
@kurt-by that's probably because you have A-only device, where boot and recovery are separate partitions.

It would be good to take that in account when copying images, as some devices should produce recovery.img, and you guys are always copying boot.img as recovery image.

**Comment by spolack** [comment]
> It would be good to take that in account when copying images, as some devices should produce recovery.img, and you guys are always copying boot.img as recovery image.

@JuniorJPDJ I dont have pretty much time to dig into this further. If you have some suggestions how to improve that exactly, please let me know.

I'm also happy to merge MRs if someone will provide.

**Comment by bxgaillard** [comment]
This should be fixed by PR #145.

**Comment by spolack** [comment]
Merdged. I'll spinup another build round for LOS 17.1

**Comment by kurt-by** [comment]
@spolack I'm ready for testing

**Comment by thrillfall** [comment]
i just tested the recovery for sargo. Works great!
This should be added as a migration path from custom builds to lineageos4micro.
1. flash the recovery
2. sideload lineageos4microg
3. done

**Comment by bxgaillard** [comment]
Recoveries are still broken for today builds (at least for bacon and avicii). It's strange since the docker-lineage-cicd container produces correct recoveries with my own builds, using the latest image from docker.io (6 days old).
@spolack: is the container up to date on the build servers?

**Comment by kurt-by** [comment]
Confirmed for lineage-17.1-20210125-microG-bacon-recovery.img
2021-01-25 05:33
6.6 MB

**Comment by kurt-by** [comment]
Bacon recovery January 26 boots as expected. Thank you. OTA update with built in updater and lineage recovery: success

**Comment by jw243** [comment]
I am not sure whether this is the same problem: Z3 recovery from February 5th is kind of broken.
It installs normally and it can be entered from a powered-off device using the key combo. However **reboot into recovery** does not work, neither from lineageOS nor from recovery itself. Because of that, OTA updates do not work, since system does not reboot into recovery.
Using twrp, reboot into recovery works as expected.

**Comment by kurt-by** [comment]
@jw243 that's a really strange error. Could you try same test with official lineageOS and lineage recovery? And it is definitively not related to the old bug.

**Comment by jw243** [comment]
I am sorry, but I am not going to start all over again with the installation process, not that my system seems to run smoothly again apart from recovery. 
However, Lineage does not seem to be necessary for the bug. If you tap **restart to recovery** in the recovery itself, recovery won't restart. Reboot hangs on first screen (Xperia logo) . Strange thing is, that the led lights up blue, as if the phone is in bootloader mode, but it stays on first screen (Xperia logo). It is exactly the same behaviour as if I reboot to recovery from Lineage itself.

**Comment by kurt-by** [comment]
@jw243 do you have some script in  /cache/recovery/openrecoveryscript
?

**Comment by jw243** [comment]
The only files in /cache/recovery/ are:
last_install
last_kmsg
last_locale
last_log
last_log.gz
Any one of them useful? There is no openrecoveryscript(?).

**Comment by jw243** [comment]
Due to severe bugs in the latest Z3-build,[see #161](https://github.com/lineageos4microg/docker-lineage-cicd/issues/161), I indeed tried the official lineage build together with this recovery. Same behaviour!

The official lineage recovery cannot installed, however, since its size is too large. This bug has been known for months now, and I really don't understand why these official recovery builds are still published on the official lineage download page.
