### ISSUE TITLE
OnePlus Nord not on download page though it is supported by lineage

### ISSUE THREAD

**Issue by Niwla23** [lineageos4microg/docker-lineage-cicd#150]
LineageOS supports the OnePlus Nord: https://wiki.lineageos.org/devices/avicii

However I can't find it by codename (avicii) or official name (OnePlus Nord)

**Comment by spolack** [comment]
Was not included in last build round. I triggered another build.

**Comment by bxgaillard** [comment]
I confirm.
For the record I have been building LineageOS for microG since avicii became officially supported by LineageOS without any issue, using the container provided by the present project, without any fancy addition.
The proprietary bits are already in the TheMuppets repository so it's really straightforward.

**Comment by bxgaillard** [comment]
Thank you @spolack!

**Comment by spolack** [comment]
build is uploaded.
