### ISSUE TITLE
No LineageOS for MicroG 18.1 builds for lavender (Redmi Note 7)

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [lineageos4microg/docker-lineage-cicd#202]
There was one single build with LineageOS 18.1 - after that, only 17.1 builds are available now. The official LineageOS builds are 18.1

Could you please elaborate if this build target is intended? Thanks!

**Comment by antoinevth** [comment]
In fact, there hasn't been any 18.1 round of builds since the first 18.1 build of lavender.
However, there has been 17.1 and 17.1 unofficial builds. 
I've just opened an issue asking for dropping older versions (e.g. 17.1) when newer versions (e.g. 18.1) are available: https://github.com/lineageos4microg/docker-lineage-cicd/issues/203
If my demand is accepted, we could hope for more frequent builds.

**Comment by bananer** [comment]
`lavender` was built for 18.1 recently.
