### ISSUE TITLE
Do I need to set CUSTOM_PACKAGES ?

### ISSUE THREAD

**Issue by skjnldsv** [lineageos4microg/docker-lineage-cicd#27]
I see in the examples that some (thea) have no `CUSTOM_PACKAGES` set and some have.

By default, (the ones that are downloadable on https://download.lineage.microg.org), is running without defining the apps good enough?
Or do we strictly have to set the apps with: `CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension`

**Comment by corna** [comment]
CUSTOM_PACKAGES can be used to add additional packages to the ROM, in addition to the ones already included in a standard LineageOS build. If you don't specify a CUSTOM_PACKAGES, the default ones will be included and the resulting image will contain the exact same packages as an [official LineageOS build](https://download.lineageos.org/).

On the other hand, if you want to integrate packages at build time (so that they reside in `/system/app` or `/system/priv-app`), you can specify them in CUSTOM_PACKAGES.

In some of the examples, some packages (like FDroid and microG) are integrated in the builds: these packages are not present in the LineageOS source tree, and must be provided externally, in our case [here](https://github.com/lineageos4microg/android_prebuilts_prebuiltapks). You can of course use our binary repository or build your own with other different packages.

The builds available on https://download.lineage.microg.org/ are built with CUSTOM_PACKAGES set to `GmsCore GsfProxy FakeStore FDroid FDroidPrivilegedExtension MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar`.

**Comment by skjnldsv** [comment]
@corna Thanks a lot for your help!!
Enjoy your week-end! :sun_with_face:
