### ISSUE TITLE
Add nio support

### ISSUE THREAD

**Issue by h0cheung** [lineageos4microg/docker-lineage-cicd#272]
Its official LineageOS 18.1 builds started on mid-February, and also has working LineageOS 19 device tree, but this project doesn't have builds for it yet.

**Comment by bananer** [comment]
since it's included [here](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets#L120), build should be included in the current round

**Comment by bananer** [comment]
It was supposed to build with the last round but that failed https://github.com/lineageos4microg/docker-lineage-cicd/issues/279

**Comment by soluzioninformatiche** [comment]
Any news on the next round?

**Comment by bananer** [comment]
Build rounds start on 1st and 15th every month. Expect a first nio build around 19th.

**Comment by soluzioninformatiche** [comment]
Thanks, I appreciate

**Comment by red-black-bonsai** [comment]
The build last month was done on the 20th, so thanks! :)

However, this month: no new build and nx563j (later in the alphabet) seems to have been built on the 15th already. (Although it seems to me the build order may have been randomized because builds don't seem to be happening in strictly alphabetical order any more?)
The plain lineage build seems to work, it was fininshed on 2022-04-16.

Did the microg build fail again for nio? And if so, is it possible to say why?

**Comment by bananer** [comment]
@red-black-bonsai on https://download.lineage.microg.org/nx563j/ i can see build from 04-09 and 04-15

18.1 builds unfortunately stopped due to a network error for the 04-15 round, expect new `nio` builds after 05-01

**Comment by petefoth** [comment]
Closing this issue. up-to-date builds for nio are availab;e
