### ISSUE TITLE
LineageOS for MicroG does not ship firmware, making upgrade very complicated. Please resolve.

### ISSUE THREAD

**Issue by HerrBert233** [lineageos4microg/docker-lineage-cicd#297]
See:
https://forum.xda-developers.com/t/rom-official-sake-12-1-lineageos-19.4392517/page-8#post-86865401

On ASUS Zenfone 8, upgrading LineageOS (from 18.1 to 19) is technically quite simple. Just sideload the newest LineageOS version. However, **not so with the LineageOS for MicroG** builds. Because they lack firmware. What we would need to do is: First revert to the stock ROM, upgrade stock ROM to Android 12, then install newest LineageOS for MicroG. Very complicated and requires full wipe in between. This is not acceptable. Only reason is because YOU for some reason decided to not include the firmware in the builds.

Why do you need to make things more complicated as they already are?? Please, just do the right thing and include firmware in your builds just as regular LineageOS builds and everyone will be happy. I don't care if it's not pure open source or whatever, or if it violates your very idealistic standards. Just do it.

**Comment by qmega** [comment]
I'm affected by this too... but can we be more civil here? I get the frustration; I spent the better part of a day this weekend unbricking my phone and setting it up again, and lost a bit of data too. But stuff like "I don't care... Just do it." doesn't seem likely to accomplish anything and isn't fun to read.

Is the exclusion of the firmware intentional, and what are the reasons for it if so? (I'm pretty new to Lineage, microG, and Android, so I'm sorry if this is common knowledge or documented somewhere I missed.) There could be security implications to that, too, right?

For the time being, could someone put a note in a file with a scary name in https://download.lineage.microg.org/sake/ and/or maybe move the 19.1 files to an "experimental" directory or something that might give pause to unwitting downloaders? Might save someone a lot of trouble. Right now the Lineage for microG instructions defer to the upstream Lineage instructions, which make the upgrade sound very straightforward but in fact result in disaster with the current lineageos4microg build on this device.

FWIW, the xda thread linked in the OP also has a suggestion that the firmware images from the upstream Lineage package could be flashed alongside the partitions that the microG version does contain for a working system. I don't think I'll have the free time to experiment with that for another 2 weeks or so, though.

**Comment by HerrBert233** [comment]
> That said, the installation zip already includes the latest version of [the corresponding firmware files in the Muppets repository](https://github.com/TheMuppets/proprietary_vendor_asus/tree/lineage-19.1/sake), which appears to be last updated a month ago.

If this was the case, people wouldn't report bricked phones, and people wouldn't observe [missing images files](https://forum.xda-developers.com/t/rom-official-sake-12-1-lineageos-19.4392517/page-9#post-86867271) in the ROM.

Yes, meanwhile there is a solution. Requires to [extract the payload.bin](https://wiki.lineageos.org/extracting_blobs_from_zips#extracting-proprietary-blobs-from-payload-based-otas), which requires to setup a python environment. Then we need to fastload 36 images files (the 18 missing ones, but all of them on both _a and _b) slots).
A bit complicated, but doable, if you know how to do all those steps.

Yeah, probably would be nice to post this in the instructions, instead of just claiming everything works the same as LineageOS. It's not. You can see it in this case. They are not the same. Your build process does not match the LineageOS build process, maybe because there are "evil" proprietary blobs you want to avoid or whatever the reason might be, but the images are not the same and thus the instructions are not the same. You need to acknowledge that and make this transparent. You can do whatever you want, but you need to be transparent about it. If you exclude proprietary blobs for whatever reason, you should people tell about it. Even if you work in your spare time, telling the truth would be the bare minimum of what needs to be done.

**Comment by FintasticMan** [comment]
There is obviously an issue, but it's not clear where the issue originated from. The docker image should build everything the same way as lineage does. Obviously it's not, and I think that only the build logs could shed light on this issue.

Please don't jump to conclusions about the intentions of the people providing these files for free. It doesn't look like @bananer (maintainer) has seen this, and I assume it wasn't tested on the Asus Zenfone 8. This means that there wasn't any knowledge of this issue, and such there couldn't have been a message explaining the issue yet.

**Comment by HerrBert233** [comment]
If this is just a _bug_ I take everything back what I said.

But would also be fine to at least mention the instruction how to properly upgrade LineageOS with MicroG.

**Comment by FintasticMan** [comment]
I think that bananer is the only one who has access to the server, so he would have to put a message there. As far as I know this issue doesn't exist for any other devices.

**Comment by HerrBert233** [comment]
I get that frustration. The original sin was that LineageOS refused to cooperate with the MicroG project. They didn't want to enable signature spoofing because of "security standards". Despite the fact that most custom ROM users will use root leaving their phone open like a barn door anyway. It _should_ not be your job to setup a build pipeline for every single device. Sadly, you still have to do this. Different story though.

And now what? The only thing I can contribute is writing detailed how-to-guides for novice users. Now since I learned that a fix is not within reach in the near future, I might actually do that, sharing my knowledge with others. Going through this workaround might be the only option for sake users for now, especially if you, like me, don't even remember what stock ROM you had before. That makes everything more complicated and without that workaround that is now luckily available, I would have had a **very** hard time to properly upgrade my phone.

**Comment by AverytheFurry** [comment]
> 

this causes issues on the pixel 4a5g too, media playback is all sped up (likely to a lack of firmware)

**Comment by AverytheFurry** [comment]
> There is obviously an issue, but it's not clear where the issue originated from. The docker image should build everything the same way as lineage does. Obviously it's not, and I think that only the build logs could shed light on this issue.
> 
> Please don't jump to conclusions about the intentions of the people providing these files for free. It doesn't look like @bananer (maintainer) has seen this, and I assume it wasn't tested on the Asus Zenfone 8. This means that there wasn't any knowledge of this issue, and such there couldn't have been a message explaining the issue yet.
> 
> There definitely hasn't been a choice to remove proprietary blobs, it is just a bug. Thank you for reporting it.

this causes issues on the pixel 4a5g too, media playback is all sped up (likely to a lack of firmware)

**Comment by bananer** [comment]
> The only thing I can contribute is writing detailed how-to-guides for novice users.

That would be a great contribution for [our website repository](https://github.com/lineageos4microg/lineageos4microg.github.io). We could even create a new "Troubleshooting" section.  If you can make sense of the HTML, add it there and create a pull request, otherwise just put your texts into an issue.

**Comment by qmega** [comment]
Finally got around to trying again on my device. Flashing the missing partitions from a stock LineageOS payload worked.

FWIW, steps I did in a hopefully somewhat followable format (happy to elaborate if anyone else is going to try it and has questions):
1. Download LineageOS for microG zip from https://download.lineage.microg.org/sake/
Verify with https://github.com/lineageos4microg/update_verifier
2. Download stock LineageOS zip from https://download.lineageos.org/sake
Can use the lineageos4microg update_verifier, but use lineageos_pubkey instead of lineageos4microg_pubkey (or use [stock LineageOS update_verifier](https://github.com/LineageOS/update_verifier))
3. Get payload.bin from both zips and extract each with https://github.com/LineageOS/scripts update-payload-extractor/extract.py
4. If using Magisk, patch boot.img (from microG) with the Magisk app and save the patched img on computer.
5. Sideload microG zip as per [normal upgrade instructions](https://wiki.lineageos.org/devices/sake/upgrade) but don't reboot into the new system yet!
6. Enter fastboot/bootloader (power off device, then hold Volume Up, Volume Down, and Power keys all at the same time).
7. Now for the interesting part. Individually flash the partitions from the stock LineageOS payload that aren't present in the microG version. Flash each to both slots. I did this with the following simple script (I used zsh, tried to make it bash-compatible but didn't try it on bash):
```zsh
#!/usr/bin/env zsh

set -euo pipefail

lineage_stock_payload_output=./lineage-19.1-20220624-nightly-sake-signed/output
lineage_microg_payload_output=./lineage-19.1-20220626-microG-sake/output

for partfile in "${lineage_stock_payload_output}"/*.img; do
  partition="$(basename "${partfile}" .img)"
  if [[ -e "${lineage_microg_payload_output}/${partition}.img" ]]; then
    echo "Skipping ${partition}"
    continue
  fi
  echo "Flashing ${partition}"
  fastboot flash "${partition}_a" "${partfile}"
  fastboot flash "${partition}_b" "${partfile}"
done
```
8. If using Magisk, flash the patched img from step 4 to boot_a and boot_b.
9. Reboot normally, and if all went well you'll be on 19.1 with all user data intact.

**Comment by viasux** [comment]
> > There is obviously an issue, but it's not clear where the issue originated from. The docker image should build everything the same way as lineage does. Obviously it's not, and I think that only the build logs could shed light on this issue.
> > Please don't jump to conclusions about the intentions of the people providing these files for free. It doesn't look like @bananer (maintainer) has seen this, and I assume it wasn't tested on the Asus Zenfone 8. This means that there wasn't any knowledge of this issue, and such there couldn't have been a message explaining the issue yet.
> > There definitely hasn't been a choice to remove proprietary blobs, it is just a bug. Thank you for reporting it.
> 
> This causes issues on the pixel 4a5g too, media playback is all sped up (likely to a lack of firmware) - I use my phone to listen to music on my commute to work, so if I can't fix this during the weekend, I may have to revert to stock lineage until a fix is available.
> 
> I successfully installed the operating system, however it appears to be a bit unstable.
> 
> I'm a bit unsure where I should be looking for firmware modules
> 
> Edit: randomly, this appears to be fixed :) - not sure why it was an issue initially and hopefully media doesnt randomly start speeding itself up again lmao

update: works perfectly since

**Comment by qmega** [comment]
This can probably be closed. The current 20.0 zip does not have this issue, and it seems unlikely anyone will resolve it for the old release at this point. (And 20.0 now has /sys/class/asuslib/charging_suspend!)

**Comment by petefoth** [comment]
Closing. Seems to be fixed according to the comments
