### ISSUE TITLE
System partition too small on alioth

### ISSUE THREAD

**Issue by gigglylo** [lineageos4microg/docker-lineage-cicd#314]
Hi, I'm using 19-20220621-microG-alioth build with nothing added. And I tried to install https://github.com/althafvly/ih8sn/commits/alioth, it's a small add-on to pass safetynet. It's only 8mb. 

The installer failed and says there's not enough space on system. 

So, I hope there's more room on system to install add-ons. Thank you for your incredible work. 

The installable zip on official alioth telegram: https://t.me/c/1482666136/33616

**Comment by D3SOX** [comment]
Why would you need that? I pass SafetyNet with just microG

**Comment by D3SOX** [comment]
Wait I forgot I have https://github.com/kdrag0n/safetynet-fix and https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf

**Comment by oceanBT** [comment]
Hi i run into a similar issue. i want to install android auto via nik-gapps as descriped [here](https://forum.xda-developers.com/t/microg-android-auto-fully-working.4319159/#post-85474691). This works great on 2 devices with microg-lineage 18 ( galaxy s10e and xiaomi mi mix2). But on my new flame (pixel 4) with microg-lineage 19 the installation fails, because there is to less space :(

i also think 200mb would be enough 

it seems to be controlled by this config/condition: https://github.com/LineageOS/android_device_google_coral/blob/lineage-19.1/BoardConfigLineage.mk#L28-L33

**Comment by Sapiosenses** [comment]
Without having looked at the details of this particular device build, it seems to me that this would be a problem for the official build for that device as well. 

In fact, it would be even worse for the official build, because if anyone wants to install original Gapps on that device, those are surely in many cases _vastly_ larger than any microG installation.

So it seems to me this should probably be brought up with the official LOS maintainer for that device.

**Comment by Iey4iej3** [comment]
Seemingly this is essentially due to https://github.com/lineageos4microg/docker-lineage-cicd/issues/358

> Without having looked at the details of this particular device build, it seems to me that this would be a problem for the official build for that device as well. In fact, it would be even worse for the official build, because if anyone wants to install original Gapps on that device, those are surely in many cases vastly larger than any microG installation.

It does not seem to be the case, since the official LOS seems to be compiled with a dynamic size of system partition.

**Comment by petefoth** [comment]
> Seemingly this is essentially due to https://github.com/lineageos4microg/docker-lineage-cicd/issues/358

#358 is currently marked 'Won't fix'

The place to 'fix' or 'patch' this issue is in the upstream makefiles for this device
https://github.com/LineageOS/android_device_xiaomi_alioth

Other upstream devices make adjustments to the space reserved for different partitions when a build is made with the `WITH_GMS` flag set `true` - see this search for some examples
https://github.com/search?q=org%3ALineageOS%20WITH_GMS&type=code

**Comment by petefoth** [comment]
I'm going to close this issue. The 'fix' for this problem is in the device-specific makefiles which are owned by the LineageOS upstream.
