### ISSUE TITLE
Add custom app with root permissions

### ISSUE THREAD

**Issue by TheLastGimbus** [lineageos4microg/docker-lineage-cicd#328]
Hi there!

My phone started being really buggy because of all Magisk/Exposed stuff for MicroG :angry:  so i finally decided I want to build my own system to have everything clean :relieved: 

I've successfuly built pure lineageos for now with your Docker ^_^ big thanks!

Now i want to start adding MicroG, and some of my own stuff: mainly, privilaged [AuroraServices](https://gitlab.com/AuroraOSS/AuroraServices), and [Acc](https://github.com/VR-25/acc)/[AccA](https://github.com/MatteCarra/AccA).

AuroraServices will be easiy, because i can copy stuff just as in [FDroidPrivilaged](https://github.com/lineageos4microg/android_vendor_partner_gms/tree/master/FDroidPrivilegedExtension). But AccA requires root :confused:

Is there a possibility i could bake-in the apk into the system while builing - so that i don't need whole Magisk/anything, and it just gets root access?

**Comment by petefoth** [comment]
I am going to close this issue because it is nothing that we will fix on our repos. But there are a cuple of wayts to do what you want
1. [This section of the README](https://github.com/lineageos4microg/docker-lineage-cicd#additional-custom-apps) described how you can add other apps to your ROM
2. I have successfully used [@sfx-android's `android_vendor_extendrom` project](https://github.com/sfX-android/android_vendor_extendrom) to make customised builds of los4mg
