### ISSUE TITLE
19.1 for target sake (zenfone 8) not updated since 26 August

### ISSUE THREAD

**Issue by Auditor08** [lineageos4microg/docker-lineage-cicd#340]
The latest build in the your repository download.lineage.microg.org/sake
For target sake (Asus Zenfone 8) is almost one month old.
Other targets were updated whenever Lineageos was updated.

**Comment by petefoth** [comment]
Closing this issue: up-to-date 19.1 & 20.0 builds for this device are available at https://download.lineage.microg.org/sake/

If you really want 19.1, then be quick, because we only keep the three mots recent builds on the download server, and the last 19.1 build is likely to disappear when we do the August build run
