### ISSUE TITLE
No updates/builds? (FP3+)

### ISSUE THREAD

**Issue by asdfgugus** [lineageos4microg/docker-lineage-cicd#387]
I saw on the website that the images are built twice a month. However there are no builds since mid December. What is the state here? 

Thanks for your effort!

**Comment by CNugteren** [comment]
I'm also waiting for a new release. To be clear, this is for the `FP3`, which had its last LineageOS 19 with microg build on 2022-12-18:
https://download.lineage.microg.org/FP3/
However, it did receive multiple regular LineageOS 19 releases since, the last one on 2023-01-30:
https://download.lineageos.org/FP3

**Comment by lebakassemmerl** [comment]
This is just a random thought, but could it be, that this issue relates to the new builds of the FP4?
Maybe there was a copy-paste error or something similar introduced within the build-script for the CI when adding support for the FP4 device?

Because I **think** the FP4 builds came out at around the same time as the FP3 builds stopped.

**Comment by genofire** [comment]
Maybe, i do not find any meta-project for that CI Pipelines, like: https://github.com/LineageOS/hudson/blob/master/lineage-build-targets

Or the CI runs itself:
https://buildkite.com/lineageos/android

So lineageos4microg looks not so transparent then lineageos for me, that is sad.

Or i am blind, please correct me.

**Comment by asdfgugus** [comment]
New update available: https://download.lineage.microg.org/FP3/
Thanks!

**Comment by asdfgugus** [comment]
@genofire I totally agree with you! I would appreciate a transparent building process as well. 
@bananer therefore I would offer you my contribution. Please let me know!

**Comment by petefoth** [comment]
I'm going to close this issue as the builds for `FP3` are now being built with no problem, and made available at https://download.lineage.microg.org/FP3/



> Maybe, i do not find any meta-project for that CI Pipelines, like: https://github.com/LineageOS/hudson/blob/master/lineage-build-targets
> 
> Or the CI runs itself: https://buildkite.com/lineageos/android
> 
> So lineageos4microg looks not so transparent then lineageos for me, that is sad.
> 
> Or i am blind, please correct me.

The CI happens on our own server

You can monitor build progress on the dedicated Matrix channel https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net
