### ISSUE TITLE
building for existing officially unsupported LOS (gts28vewifi)

### ISSUE THREAD

**Issue by maitra** [lineageos4microg/docker-lineage-cicd#401]
[The site](https://los.rockhost.se/gts28vewifi) contains unofficial 17.1 builds for gts28vewifi (though I can not seem to extract the sha256 keys to check).

My question is: do I use the instructions for the unspported build [here](https://github.com/lineageos4microg/docker-lineage-cicd) for building LineageOS with Microg? I am a little confused because I have the LOS already built in a zip, courtesy the unofficial build.

Btw, anyone know how to fix the sha256 keys issue above? My issue is that the sha256 sum link goes back to the LOS zip.

**Comment by kurt-by** [comment]
Looks like your unofficial builds are made with a copy of original lineageOS device trees. 
https://gitea.wickenberg.nu/Piteball/android_device_samsung_gts28vewifi
I would try to build gts28vewifi like a supported device.

**Comment by petefoth** [comment]
> My question is: do I use the instructions for the unspported build [here](https://github.com/lineageos4microg/docker-lineage-cicd) for building LineageOS with Microg? I

Yes the instructions should work, but you will need 
- a manifest specifying where to find the necessary device and kernel trees, and proprietary vendor blobs. They all exist in the LineageOS github repos, but only in `lineage-16.0` branches. If you want a later linegae version you would need to pulls the source from elsewhere
- if the vendor blobs are not available in a git repo that can be specified in your manifests, then you will need to extract the vendor blobs yourself. 

I am going to close this issue, since we only support building `lineage-18.1` and newer versions. IF you need further help or advice with your builds, feel free to ask in [the 'LineageOS for microG' XDA forum](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/)
