### ISSUE TITLE
Problems flashing devices which have their recovery in vendor_boot partition

### ISSUE THREAD

**Issue by Yannik** [lineageos4microg/docker-lineage-cicd#405]
Hi,

I've recently tried to install lineageos w/microg on bluejay (pixel 6a).  
I have used the files from https://download.lineage.microg.org/bluejay/.

There are a few things which are not working right now:
1. The [installation guide](https://wiki.lineageos.org/devices/bluejay/install#booting-a-custom-recovery-using-fastboot) mentions flashing the `vendor_boot` partition with a `vendor_boot.img` file.  
This file does not exist on the [download page](https://download.lineage.microg.org/bluejay/) for the build from the 6th of march.  
I thought this should've been added with [this](https://github.com/lineageos4microg/docker-lineage-cicd/commit/ba58e6bd8f36222c8f8ad975c4abad9bafbf236d) 3rd of february commit from @bananer, but apparantly something is not working here.

2. I have extracted `payload.bin` from the zip, and extracted that using `payload_dumper`. Then I flashed `vendor_boot.img` which I got from there.
Unfortunately, booting into recovery did not work. Instead, the device fails to boot.

**Comment by petefoth** [comment]
The section of the installation guide you quote is describing how to install a recovery image. 

When I started  working with LOS-based custom ROMs, Lineage OS used to build only the ROM zip files, and the installation instructions pointed to TWRP as the recovery to use. Then they started building their own recovery, making it available as images named e.g. `lineage-19.1-20221215-microG-sunfish-recovery.img`. Now they make a number of images, which differ for each device e.g.
-  [bluejay](https://download.lineageos.org/devices/bluejay/builds)  has `boot.img dtbo.img super_empty.img vbmeta.img vendor_boot.img` - we have only `boot.img`
- [instantnoodle](https://download.lineageos.org/devices/instantnoodle/builds) has `boot.img dtbo.img recovery.img super_empty.img vbmeta.img` (so no `vendor_boot.img`) - we have only `boot.img` and `recovery.img`
- [sunfish](https://download.lineageos.org/devices/sunfish/builds) has `boot.img dtbo.img super_empty.img vbmeta.img`  (so no `vendor_boot.img` or `recovery.img`)  - we have only `boot.img`

I have no idea **why** the available images vary between devices, and between our builds and official LOS builds and, at the moment I don't have time to go digging to find out the answer. Or to find out why /e/OS and IodéOS have only `recovery` images.

From my understanding, at the moment, to install a los4mg ROM file (or any other custom ROM), you need only the ROM zip file, and a recovery to flash and use to install the zip file. The key problem seems to be working out ***which*** of the available `.img` files contains the recovery. In the case of `bluejay`, I would _**guess**_ that the recovery is **_EITHER_** our `lineage-20.0-20230701-microG-bluejay-boot.img` **_OR_** LOS's `vendor_boot.img` **_OR_** LOS's `boot.img`

The only way to  check would be to try all three. Sadly we don't have access to one of these devices, so if you could try it out and report back that would be really good. My ideal answer would be that our ROM can be installed with one of our images, whether that is a `boot.img` or a `recovery.img`

I'm going to assign this issue back to you. If you don't have time to do the checks, then feel free to unassign yourself and/or assign it back to me.

Thanks

**Comment by Yannik** [comment]
@petefoth For bluejay, the [lineageos installation guide](https://wiki.lineageos.org/devices/bluejay/install) explains the procedure in which partitions need to be flashed. [First](https://wiki.lineageos.org/devices/bluejay/install#flashing-additional-partitions), `boot` and `dtbo` need to be flashed. [Then](https://wiki.lineageos.org/devices/bluejay/install#booting-a-custom-recovery-using-fastboot), `vendor_boot` needs to be flashed.

I believe making these files available for download on https://download.lineage.microg.org/bluejay/ will solve this issue.

**Comment by petefoth** [comment]
As I wrote in response to another issue ( #453 )
> What files / images are produced by the build for specific devices is determined by the source files and makefiles which, for us, come from the LineageOS repos. Recent LineageOS builds are now producing these .img files. Our latest build does not, presumably because the changes in the LineageOS repos were made after we synched those repos for the July build run (on 1st July).
>
> I would guess / hope that our next build run will pick up those changes and should therefore produce the relevant.img files. Let's wait and see. In the mean time, you can try using the LOS provided images.

**Comment by Yannik** [comment]
@petefoth I think there is a misunderstanding here. In #453, the user extracted the relevant `.img` from the payload.bin in the zip. This worked for them.

However, the suggestion is to make these img's available for direct download (as does lineageos), without having to extract the zip and unpack `payload.bin`. This does apparantly NOT happen automatically (e.g. for bluejay, these downloads have been provided since atleast march, when I opened this issue).

**Comment by petefoth** [comment]
OK - sorry for the misunderstanding.

So looking more closely, we will need to make some changes in our post-build processing: currently, of the `.img` files created by `mka bacon`, we are only copying across the `recovery`, `boot` and `vendor_boot` images to the .zips directory. We need to also include `dtbo`, `super_empty`, and `vbmeta` images as well.

This looks to be a simple change, in [this line of our `build.sh`](https://github.com/lineageos4microg/docker-lineage-cicd/blob/efa38ce2de0f6ad0c76d353485c1d0fa95e0e1d9/src/build.sh#L368C24-L368C49)

I will try making the change. If I have time to test it, and it does not cause any problems, then I will puch the chnage to our `master` branch. However, I can't promise that I will have time to do that before the August build run starts at midnight tonight. If not, then the change will not happen until the September build run.

Thanks for your help

**Comment by Yannik** [comment]
@petefoth I don't think that the only problem is that `dtbo`, `super_empty` and `vbmeta` are missing. To me it seems like this part of `build.sh` isn't working at all.

E.g. for bluejay, `vendor_boot` is being build (it's part of `payload.bin`), but it is not published on the [bluejay download page](https://download.lineage.microg.org/bluejay/).

**Comment by petefoth** [comment]
The `.zip` and`.img` files are produced by `mka bacon`. If `mka bacon` builds the 'missing' image files, then they should be available in the `out` directory.

If `mka bacon` has built those files, added them to `payload.bin` and removed them from  the `out` directory, then the LineageOS build process must be doing some additional post-build processing that is **not** mentioned in [their build instructions](https://wiki.lineageos.org/devices/bluejay/build). 

That processing must be device-specific, since the download pages for [e.g. `enchilada`](https://download.lineageos.org/devices/enchilada/builds) do have `boot` and `dbto` images, but not `vendor_boot` or `super_empty`. 

Our `build.sh` can deal with `.img` files that are present in `out` (and I am testing the change which would handle the 'missing' images). I have no idea how we would go about adding device-specific processing to extract them from e.g. `payload.bin` or wherever the LOS post-build processing has hidden them.

When the test build has completed, I will check what `img` files **are** present in the `out` directory.

**Comment by Yannik** [comment]
> When the test build has completed, I will check what img files are present in the out directory.

Yeah, that sounds like a reasonable next step. Which device builds are you checking this for?

**Comment by petefoth** [comment]
[This commit, ](https://github.com/lineageos4microg/docker-lineage-cicd/pull/456/commits/ba64ea53b02642627df4bae935318dd8da20f54a) merged in PR #456, ensures that `dtbo`, `super_empty` & `vbmeta`  `.img` files will be copied to the `zips` directory, and then to the download server ***if*** they are present in `out/target/product/<device-name>` at the completion of the `mka bacon` command.  Whether or not they are present in `out/target/product/<device-name>` is determined by the device-specific makefiles from the LOS repos and is therefore  ***outside our control***.
I strongly suspect that the last two, probably along with `vendor_boot.img` will not be present: in my experience, they are built and packaged into the ROM zip files. LineageOS are choosing to make them available, and where they do, they must be doing further post-build processing to extract them. I believe - though I cannot prove it, as I have no access to a device which uses these files during installation - that installation can progress by using  ***the most recent version of those files from the LineageOS download pages***

- The best we can do,  is to add some words in our `README.MD` along the lines of
> If the Lineage OS installation instructions for your device reference files (e.g. `vendor_boot.img`, `vbmeta.img`) that are not available in [our download page](https://download.lineage.microg.org) for your device, then you should use the most recent version of those files from the LineageOS download pages

I have added this as something to be done in [ Documentation updates #454 ](https://github.com/lineageos4microg/docker-lineage-cicd/issues/454). I will close this issue when that issue is complete

**Comment by Lanchon** [comment]
> * The best we can do

what would stop you from fishing the missing files from the wherever they are found in the build dirs?

**Comment by Yannik** [comment]
@petefoth 

>  Whether or not they are present in out/target/product/<device-name> is determined by the device-specific makefiles from the LOS repos and is therefore outside our control.

Can you link one of these device-specific makefiles? Maybe it's possible to parse them in someway to determine the required files?


> I strongly suspect that the last two, probably along with vendor_boot.img will not be present: in my experience, they are built and packaged into the ROM zip files.

In this case, I agree with @Lanchon, can't we copy these `.img`'s from the build dir? 
If this is not possible for some reason, we could still use [payload_dumper](https://github.com/vm03/payload_dumper) to extract these specific `.img`'s from `payload.bin`.

**Comment by petefoth** [comment]
> what would stop you from fishing the missing files from the wherever they are found in the build dirs?

Lack of time, resources and motivation :)

The scope of this project is to make regular builds of the los4mg ROMs - the  ROM zip file - for around 220 devices, and make them available for download and installation, either manual or OTA. For some devices, other build artefacts (such aas `recovery.img` or `boot.img` files **_may_** be produced and made available, **_if_** the makefiles we use - the device-specific makefiles from the LOS repos - are written to make those artefacts available in the `out/target/product/<device-name>` when `mka bacon` is run.

Producing and/ or making available any other artefacts - such as custom recoveries or files to be used to install the ROMs - is, and so far as I know always has been, **_outside the scope of his project_**.  If such artefacts are needed to install the ROMs, then the versions made available by LineageOS can be used, and should work

> Can you link one of these device-specific makefiles? Maybe it's possible to parse them in someway to determine the required files?

They are device specific, and are available from the [Lineage OS repos](https://github.com/LineageOS). This project does not edit or patch them: we fetch them using `repo sync` for the Android build tools to use when building whatever artefacts they specify. 

If you wanted to change the artefacts produced when building .e.g. `bluejay`, (mentioned in the original post in this thread), then the way to do it would be to 
- make changes in the [`android_device_google_bluejay`](https://github.com/LineageOS/android_device_google_bluejay) and/or [`android_kernel_google_bluejay`](https://github.com/LineageOS/android_kernel_google_bluejay) repos, and any other repos specified in the LineageOS manifests
- get those changes accepted by the LineageOS project

We would pick up the changes and the artefacts would be produced and made available.

I have no idea ***how*** LineageOS go about obtaining the extra artefacts, except that it is not by running `mka bacon` on their published makefiles. Maybe they do parse them in someway to determine the required files, copy them from the build dir, or use [payload_dumper](https://github.com/vm03/payload_dumper) to extract them.

Whatever they do is not something we will do because, as I have stated before, it is outside the scope of what this project does. If you need these artefacts for whatever purpose when installing the ROMs this project makes, then use the versions made available by LineageOS.

I'm starting to repeat myself :( so I won't be contributing further to discussion of this issue, except to close it when the documentation changes mentioned above have been implemented and merged.

**Comment by Lanchon** [comment]
> I have no idea how LineageOS go about obtaining the extra artefacts, except that it is not by running mka bacon on their published makefiles.

i don't see why you say that. if they are bundled in the payload they sure are somewhere in the build dir. for sure each missing file would be in the same place for all devices that build it. it would just be a matter of picking this file from here and that one from there, if they happen to exist.

@Yannik if you want, try building your device without cleaning the build afterwards, then locate your missing file somewhere in your lineage mount directory.

**Comment by Yannik** [comment]
I have done more research on this.

The images are created by the script `/srv/src/LINEAGE_20_0/build/make/tools/releasetools/add_img_to_target_files.py` using `/srv/src/LINEAGE_20_0/out/target/product/$codename/obj/PACKAGING/target_files_intermediates/lineage_$codename-target_files-eng.root/META/dynamic_partitions_info.txt` and `/srv/src/LINEAGE_20_0/out/target/product/$codename/obj/PACKAGING/target_files_intermediates/lineage_$codename-target_files-eng.root/META/ab_partitions.txt`

They are placed into `out/target/product/$codename/obj/PACKAGING/target_files_intermediates/lineage_$codename-target_files-eng.root/IMAGES/`:

```
$ ls /srv/src/LINEAGE_20_0/out/target/product/bluejay/obj/PACKAGING/target_files_intermediates/lineage_bluejay-target_files-eng.root/IMAGES/
boot.img     product.map      system_ext.img  system.map        vbmeta.img         vendor_boot.img  vendor.img
dtbo.img     pvmfw.img        system_ext.map  system_other.img  vbmeta_system.img  vendor_dlkm.img  vendor.map
product.img  super_empty.img  system.img      userdata.img      vbmeta_vendor.img  vendor_dlkm.map
```

I will create a PR to correctly copy the images from this directory.

**Comment by petefoth** [comment]
Thanks for digging. 

> The images are created by the script `/srv/src/LINEAGE_20_0/build/make/tools/releasetools`

In my local build tree, `git remote -v` in `/srv/l20/src/LINEAGE_20_0/build/make` gives
```
github	https://github.com/LineageOS/android_build
```
> I will create a PR to correctly copy the images from this directory.

Are you planning to copy ***everything** from that directory, for every device? 

Or is it possible the the necessary files from that directory vary per-device? If that is true, then the fix is to amend the upstream device-specific make files and/or build scripts. We are not in a position to test and maintain device-specific code in this project

**Comment by Yannik** [comment]
@petefoth I am planning to copy only `recovery boot vendor_boot dtbo super_empty vbmeta` and only if they are present. (not all of these are built for all devices). This seems to be the way LineageOS is doing it.

**Comment by petefoth** [comment]
Returning to the original post in this thread

> 1. The [installation guide](https://wiki.lineageos.org/devices/bluejay/install#booting-a-custom-recovery-using-fastboot) mentions flashing the `vendor_boot` partition with a `vendor_boot.img` file.
>        This file does not exist on the [download page](https://download.lineage.microg.org/bluejay/) for the build from the 6th of march.

If the LineageOS installation instructions for this device require the use of files which are not delivered by this project, then you should use the versions made available by the LineageOS project

**Comment by petefoth** [comment]
Here's my final opinion on this issue (apologies - it's a bit long)

This project makes and publishes los4microg ROMs. The deliverable files that we make available for download  for these ROMs are
- the ROM zip file -`lineage-<branch>-<date>-microG-<devicename>.zip`  and associated `sha256sum`
-  other build artefacts (e.g.`recovery.img`,  `boot.image`, other `.img` files, `.prop` files) and associated `sha256sum`s ***if*** the upstream device-specific makefiles cause those files to be made available ***in the `out` directory*** (i.e.  `out/target/product/<devicename>`)

This project does not 
- provide installation instructions or any other device-specific documentaion
- produce or maintain any device-specific code
- make available 
    - any other build artefacts  that the upstream device-specific makefiles cause to be placed in ***subdirectories*** of the `out` directory, or elsewhere in the build tree
    - any third party tools (e.g Custom recovery tools such as TWRP)

As well as producing the LineageOS ROMs, the LineageOS project also produces a lot of  support documentation,  much of it device-specific,, including installation instructions and (in the past at least) links to other device- or manufacturer-specific tools (e.g. TWRP) or documentation (e.g. how to obtain a code to unlock the bootloader). 

As part of this device-specific support, as well as the ROM files (the `.zip`,  the `sha256sum` and the `.img` files from the `out` directory,) LOS also make available some other files that are needed in the process of installing the LOS ROM (and other custom ROMs) over the stock device software.  For some devices, the files include binary files and other build artefacts that the makefiles make available in subdirectories of the `out` directory and / or elsewhere in the build tree

All of this user support output - documentation,  links to other sites and binary files, build artefacts from subdirectories of  the `out` directory is, in my opinon, currently ***outside the scope of this project***.  This issue is suggesting that we should widen the scope of the project, to include at least some of it - the publication of other build artefacts.  Even if this were good idea (and personally I don't think it is) the project does not have the time or resources or people to increase its scope in this way.

In ***our*** documentation, we can and should direct users to the LineageOS project for device specific support, including installation instructions and (crucially as far as this issue is concerned) for ***any files needed by the installation process that are not available on our download site***. We don't currently do that, and as mentioned above that will be changed along with other issues in our documentation

So, having said all that, I intend to do the following:
- Mark this defect with `Wont fix`, `Not in scope`, and `Fix in documentation` labels, so that other users of this issue tracker can see what will be happening with the issue in the immediate future;
- Ensure that our documentation is changed to make clear that, where files needed in the installation process are not available from us, the LineageOS versions can and should be used
- Leave this issue open, so that:
    - anyone interested can continue the discussions;
    - any other project maintainers can revisit and change my decision if they see fit to do so.
- Ask @bananer - the other ative maintainer of the project, to reveiw this issue and my decisions / actions
- Unsubscribe from the thread, so I can focus my efforts on some of the other issues and problems that are currently impeding our project goals of (continuing to) build and publish regular, up-to-date los4microg ROMs for around 200 devices.

I am sure many of the contributors to this thread will disagree with my opinion, my arguments and my actions. That is unfortunate, but I am acting in what I believe to be in the best interests of the project.

Thank you for all your contributions

**Comment by Lanchon** [comment]
this is bad call. some of these files can be specific to the build or builder: some may need to be in sync with the rom, some may encode the public signature of the builder, etc. these files are device specific and have been included in the output of lienageos for a reason by people who know. but it's your call and it's been decided. :+1:

**Comment by Yannik** [comment]
@petefoth 

Yup, bad call indeed. Requiring users to download files from 2 different sources (lineageos4microg AND LineageOS) does not only make the installation process unnecessarily complicated for beginners, but it is also not going to work due to signature mismatches between the build artifacts as both projects use different signing keys.

As far as I understood, [this line](https://github.com/lineageos4microg/docker-lineage-cicd/blob/4420cb1f64ee3218dd4035a5b5fd96886acfd50e/src/build.sh#L373) actually intended to provide `vendor_boot` etc. via the  lineageos4microg project. My commit simply makes it actually work.

**Comment by petefoth** [comment]
OK. Please can you explain to me
1. What are the different images required ***for***? in what operations are they needed for?
2. Are they required for ***all devices***
3. If they are required, why can they not be provided by changing the upstream device-specific makefiles to place them in the .out` directory?

**Comment by Yannik** [comment]
@petefoth 

> What are the different images required for? in what operations are they needed for?

* vbmeta contains verification data (e.g. cryptographic digests) for verifying boot.img , system.img and others.
* dtbo contains device tree blobs (which might be required by boot.img/vendor_boot.img), see https://source.android.com/docs/core/architecture/dto
* vendor_boot contains vendor-specific information required by the boot partition (earlier, this was included in the boot partition)
* super_empty empties out the super partition to make space for the new sizes of the system partition and others.

`super_empty` is only required for installation, the others can theoretically also be changed during updates.

>  Are they required for all devices

No. But it will become more common over time. E.g. `An ARM64 device launching with Android 11 on the 5.4 Linux kernel must support the vendor_boot partition and the updated boot partition format to pass testing with the GKI.`

> If they are required, why can they not be provided by changing the upstream device-specific makefiles to place them in the .out` directory?

That could certainly be done, however, as LineageOS does *not* require that, as it uses the `.img`'s from the `IMAGES` directory. So that would be a never ending battle, as new devices will not necessarily abide by lineageos4microg's expectations. 

Simply providing the `.img`s from `IMAGES` *if they exist* (like LineageOS does) seems to be the solution with the least amount of problems.

Please note that currently installing lineageos4microg does NOT work for the devices which require these partitions, unless they know how to use payload_dumper (which most users don't).

**Comment by petefoth** [comment]
Thanks. You have explained what these images contain (which I had mostly worked out from reading the https://source.android.com/docs/core/architecture/ pages).

What I am still not clear on is ***when*** and ***how*** these images are used. My view of the use cases we suppors is this:

1. A user's device runs the manufacturer's stock ROM. They wish to replace it with a custom ROM, in our case our los4microg ROM. To accomplish that they will need to follow the instructions from the LineageOS device-specific wiki pages for the following operations:
    1.  Unlocking the bootloader
    2. Installing a custom recovery, provided by LineageOS, by us, or by a third party
    3. Installing our custom ROM (i.e the main `zip` file we make available)
    4. Installing updated versions of our ROM either
        1. Manually, but following similar steps as for 2. (if the custom recovery installed in that step is no longer present on the device) and 3.
        2. by OTA using the updater app

In which of those steps do they need to use the images that we do not currently make available?

Why can they not use the version provided bu LOS? I know they will be signed by different keys, bit - as far as I am aware - the recovery used to flash a ROM does not need to be signed with the same keys as the ROM being installed.

Thanks again for helping me get my head round all this :)

> Please note that currently installing lineageos4microg does NOT work for the devices which require these partitions

Which of the steps described above does not work?

And is there a list of these devices? Or can it be deduced from looking at the LOS Device wiki pages?

**Comment by Yannik** [comment]
@petefoth In early versions of android, the process was as you described. However, nowadays, recovery is usually contained within the boot partition, and all the previously described constraints (signature checks etc.) apply. Also additional partitions (e.g. dtbo) need to be flashed for the recovery to work, which you didn't include in your steps.

> And is there a list of these devices? Or can it be deduced from looking at the LOS Device wiki pages?

There is no list, but if you go through the installation instructions for each device you will see which partitions will need to be flashed with fastboot. Generally, this only affects newer devices.

**Comment by petefoth** [comment]
Thanks again.

I've added a couple of questions to one of your commits.

Also you have pushed two separate commits that look very similar. Which one should be used. 

Making changes to the `master` branch is easier if they are in Pull Request, from a tested branch, with some information on what testing was done, and what the result of the tests was

**Comment by Yannik** [comment]
@petefoth I'm confused. There is a PR and it only contains one commit. It also contains the results of my build test. Where exactly can I find your questions? There are none in the PR. Would you mind posting them there?

**Comment by petefoth** [comment]
I can see these two  commits in this thread

https://github.com/Yannik/docker-lineage-cicd/commit/c724eeaca3cba2ca3668e6acdb29aa4c7d89a573

https://github.com/Yannik/docker-lineage-cicd/commit/caa009fa6bcbe801ab8beb3a02fe9eadc5ef3860

I added question to the second

I have now found the PR (which doesn' t seem to be linked in this thread. If it is, then I am going blind :) )

https://github.com/lineageos4microg/docker-lineage-cicd/pull/467

I have copied my questions from the commit to the PR. The second question is covered in the PR, but not the first

I will look at this again tomorrow. - ots getting late :)

**Comment by Yannik** [comment]
@petefoth the commit references in issues are automatically created by github. They are more of an "something happened" notification and can be outdated. Unfortunately, I still can't see your comment in the PR.

**Comment by petefoth** [comment]
While the August build run has been proceeding I have been making builds of IodéOS. They build without docker, using `lunch`, `mka` etc. They build by calling `mka dist` rather than `mka bacon` which alongside the ROM zip file produces an ...img.zip` file which
- contains all the required `.img`.files
- can be flashed using `fastboot update...`

This strikes me as a better way of shipping `.img` files, as well as simplifying the installation process.

I am going to experiment with making los4microg builds this way. **_If_** it works, it may be worth modifying our `build.sh` to call `mka dist` instead of `mka bacon`

**Comment by Yannik** [comment]
@petefoth 
Are you sure that `fastboot update` is supported for all devices? 
My experience has been that available fastboot commands differ greatly between devices, most of them having rather poor support for anything besides `fastboot flash`.

**Comment by Yannik** [comment]
@petefoth 
Also, this would mean that microg for lineageos installation would differ from the LineageOS installation guide (which is usually quite good).  
Therefore, microg for lineageos would need to provide their own installation guides - not sure if this is really feasible (you cannot simply say run `fastboot update` and that's it - for example device unlocking differs between devices! the lineageos installation guides explain all of that.).

**Comment by Yannik** [comment]
@petefoth  
> > My experience has been that available fastboot commands differ greatly between devices,
> 
> And my experience is that the commands differ between _**fastboot versions**_. So we would add some words if we mention `fastboot` in our docs that say 'please download the latest version of fastbot at https://developer.android.com/studio/releases/platform-tools.html'

No matter the fastboot client version, there is still a lot that depends on the particular implementation of the fastboot daemon running on the device. At least from my experience.

> Anyway, this is all hypothetical until I - or someone else - have time to experiment with using `mka dist` instead of `mka bacon` to make our builds :)

In this case, would you be open to merging the PR (for now)? :-)

**Comment by petefoth** [comment]
> In this case, would you be open to merging the PR (for now)? :-)

As I said [in the PR](https://github.com/lineageos4microg/docker-lineage-cicd/pull/467#issuecomment-1667604741)

> I will merge, but under protest ;)

And I will add, 'for now, until a better solution is available' ;)

**Comment by Yannik** [comment]
@petefoth That's great, but *when* will you merge it? :)

**Comment by vanMacG** [comment]
> @petefoth That's great, but _when_ will you merge it? :)

The answer is in the very same comment in the PR...

> As I said [in the PR](https://github.com/lineageos4microg/docker-lineage-cicd/pull/467#issuecomment-1667604741)

**Comment by Yannik** [comment]
@vanMacG Oh sorry, I missed that bit. Thanks for the heads up!

**Comment by petefoth** [comment]
More information on `mka dist`(or `make dist`) here:
https://source.android.com/docs/core/ota/tools
and here
https://source.android.com/docs/core/ota/dynamic_partitions/implement#factory-images


According to [this](https://android.googlesource.com/platform/build/+/master/Usage.txt) the purpose of the `dist` build target is 
> Copy into ${DIST_DIR} the portion of the build that must be distributed

Which seems to be exactly what we want. The output is device-dependent, determined by the device-specific makefiles. So we would publish
1. The ROM `.zip` file
2. The flashable `img.zip` file containing all the `.img` files needed for this device

This is looking a lot like `a better solution` :)

Testing to be done, when the build run finishes!

**Comment by petefoth** [comment]
> and not including them causes your builds to be incomplete.

From what I understand
1. they **are** present in our ROM zip file, the question is whether we need to deliver them ***separately*** from the ROM zip file. 
2. they are needed separately the first time a user installs a custom ROM, which is why  LOS needs to ship them
3. my view of the installation process is that users follow the installation instructions from LOS, using the `.img` files provided by LOS  up to and including the step of installing a custom recovery - LOS's recovery in this case. Then they use that recovery to install our ROM zip file (including our built versions of these images). Updates - containing our built versions of the images - arrive OTA and are flashed by our signed version of the  Updater. Are you saying that a custom recovery built and signed by LOS can not or should not be used to flashing a ROM zip file built and signed by us?

**Comment by Lanchon** [comment]
your assumptions might not hold. recovery and android can now share a bunch of stuff depending on the device, starting with the kernel, so flashing system actually changes the recovery to a mix of LOS and L4M blobs. are you **sure** you are publishing the right set of partial files (ie: all signatures for partitions you publish but none for partitions you dont) for **all** devices? further, are you willing to subject users to this untested mix of blobs knowing that an issue can have very severe consequences for users? (for those who signatures actually matter: those that relock). my opinion is simple: this project should do exactly what LOS does. they publish files for each device in a generic way, and L4M should copy that generic way and publish those same files for each device. other options are inferior and more dangerous. it's totally ok to say, well i don't want to spend time on it. but opposing to this in principle is what i try to point out is the wrong way around it.
