### ISSUE TITLE
lemonadep 20.0 fails to compile

### ISSUE THREAD

**Issue by ShadwDrgn** [lineageos4microg/docker-lineage-cicd#406]
Log:
https://cloud.1ez.us/index.php/s/488D3LBd2NYTax7
bash script being run to compile:
#!/bin/bash
docker run --rm --name android -e "BRANCH_NAME=lineage-20.0" -e "DEVICE_LIST=lemonadep" -e "SIGN_BUILDS=true" -e "RELEASE_TYPE=user" -e "WITH_GMS=true" -e "SIGNATURE_SPOOFING=restricted" -e "ZIP_SUBDIR=false" -e "OTA_URL=https://lineage.1ez.us/" -v "/mnt/ds16_backups/android/lineage:/srv/src" -v "/mnt/ds16_backups/android/keys:/srv/keys" -v "/mnt/ds16_backups/android/zips:/srv/zips" -v "/mnt/ds16_backups/android/logs:/srv/logs" -v "/mnt/ds16_backups/android/ccache:/srv/ccache" -v "/mnt/ds16_backups/android/local_manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd

Not sure what to do here. I haven't been able to get it to compile with 19 either :~(

**Comment by petefoth** [comment]
The interesting bit of the log file is near the end
```
[ 66% 109048/165224] Verifying uses-libraries: external/chromium-webview/prebuilt/arm64/webview.apk
FAILED: out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/webview_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  external/chromium-webview/prebuilt/arm64/webview.apk )"
zipro W 03-31 22:02:00 19809 19809] Error opening archive external/chromium-webview/prebuilt/arm64/webview.apk: Invalid file
ERROR: dump failed because no AndroidManifest.xml found
error: Command '['out/host/linux-x86/bin/aapt', 'dump', 'badging', 'external/chromium-webview/prebuilt/arm64/webview.apk']' returned non-zero exit status 1
```
I bumped into this error in one of my recent builds, and I'm pretty sure I got round it either by doing a clean sync of the whole source tree, or by deleting the `external/chromium-webview/` directory tree. I **think** the problem is that LOS no longer uses the `external/chromium-webview/`  component, and so it should no longer be present in the build source tree, but it was present for earlier builds, and doesn't get deleted when docker does a `repo sync`

**Comment by ShadwDrgn** [comment]
I deleted everything but the logs directory entirely and it did succeed. thanks for this!
