### ISSUE TITLE
S9 official build with microg?

### ISSUE THREAD

**Issue by chrisgee** [lineageos4microg/docker-lineage-cicd#437]
Hey,

I see that lineageos as of 20 supports S9 officially (again). 

https://download.lineageos.org/devices/starlte/builds

Are you planning to also support it. Do you have a time line?

Chris

**Comment by chrisgee** [comment]
OK. my info was outdated. It is already supported. Thanks!

**Comment by chrisgee** [comment]
Oh, sofar only boot and recovery... reopening

**Comment by petefoth** [comment]
Looking at the logs for the June build run (which was the first to include this device), the build succeeded, but the an 'out-of-disk space' error occurred when copying the ROM zip file to the download server. I'm not sure whether the problem was on the build server or the download server.

I will keep an eye on the current build run. With the luck the build will be fine. If not I'll investigate further

**Comment by cgrigis** [comment]
[The S9+ build](https://download.lineage.microg.org/star2lte/) seems to be empty... same reason?

**Comment by petefoth** [comment]
Looks like it - there's an `rsync` error in the log file. Let's wait for he July build run to get to these devices

**Comment by petefoth** [comment]
I'll close this issue: for both devices
- the June builds have been `rsynch`ed to the download server
- a new July build has been made and successfully synched

**Comment by chrisgee** [comment]
Just to confirm. June build has been installed by me on starlte. Works as expected so far.
