### ISSUE TITLE
F(x)tec Pro1 X (pro1x) builds missing?

### ISSUE THREAD

**Issue by Skirmisher** [lineageos4microg/docker-lineage-cicd#440]
There don't seem to be any OTA images available for [`pro1x`](https://download.lineage.microg.org/pro1x/), even though the boot and recovery images are there, and LineageOS upstream builds for the device are available. (The predecessor `pro1` appears to build successfully, and is indeed outwardly similar to `pro1x`, but has a different SoC.) No sign of `pro1x` in the [builder feed](https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net) either...

**Comment by petefoth** [comment]
Last month was the first attempt to build for this device. The build succeeded, but the copy to the download server failed, probably due to a broken comms link
<details>

<summary>**Log output**</summary>

```
lineage-20.0-20230608-microG-pro1x.zip
rsync: [receiver] write failed on "/mnt/archive/zips/pro1x/lineage-20.0-20230608-microG-pro1x.zip": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(379) [receiver=3.2.4]
rsync: [sender] write error: Broken pipe (32)

```

</details>

July build are in progress: they've currently reached `dre` from [the list of build targets](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets), so they should reach `pro1x in the next week or two. Sorry for the delay :)

Looking at the builder feed, there is gap between [`starting build for pro1`](https://matrix.to/#/!kKoGaPHPftqoYWDDCu:matrix.domainepublic.net/$yfoJvWucixSKUE4NwM5Kp0yvkmmmH3QUoAKlgTFw4Sg?via=gnugen.ch&via=matrix.org&via=matrix.domainepublic.net) at 20:26 on 08 June, and `Completed build for pyxis` at 02:21 on 09 June. Probably caused by the same comms breakage.

**Comment by Skirmisher** [comment]
Gotcha, so it was just bad luck haha. Glad it should be smooth sailing otherwise :)
