### ISSUE TITLE
Proposal for Synchronization of System Updates between Official LineageOS and LineageOS for microG

### ISSUE THREAD

**Issue by Subtly7360** [lineageos4microg/docker-lineage-cicd#471]
Dear LineageOS and LineageOS for microG Development Teams,

I am an enthusiastic user of both your projects. The incredible work you have put into creating LineageOS and the fusion of microG services into the LineageOS for microG variant provides users like myself a privacy-respecting, open-source operating system for our devices.

However, I have noticed an inconsistency concerning the system updates between LineageOS for microG and the official LineageOS. Even though new updates are available on the LineageOS official website, LineageOS for microG frequently displays that the system is up-to-date, resulting in a delay in receiving the most recent features and security patches.

This inconsistency could be due to various factors – from differing firmware signatures to additional modifications unique to LineageOS for microG.

Certainty there is a room for improvement. Thus, I propose a synchronization mechanism to keep system updates between the official LineageOS and LineageOS for microG streamlined. This would enable users of LineageOS for microG to receive timely updates and security patches consistent with the users on the official LineageOS.

Creating a harmonized update cycle between both projects will significantly benefit users by ensuring the availability of the latest updates.

Thank you for considering this proposal. I am certain that such an enhancement will eliminate the disparity between the system updates of the two versions, thereby improving the user experience significantly.

Yours sincerely,

Srozg Lien

**Comment by ArchangeGabriel** [comment]
Everyone would want that, but this is currently not possible: the LineageOS for microG project only has the server ressources for doing one build per month (because yes, since this is not LineageOS but LineageOS for microG, builds are different, incompatible and must be done for each device). That is why you only see one update per device per month (or even less when they are build failures not solved), and unless you are able and want to give large building ressources to the project, this situation is not going to evolve anytime soon.

**Comment by petefoth** [comment]
Thanks for the suggestion but, as @ArchangeGabriel it is not going to happen.

- This project is not associated with LineageOS - we only use their public sources.
- LineageOS have many contributors, and - I guess - access to significantly more computing resources for building than this project

Closing this issue
