### ISSUE TITLE
Camera is not working only with microg flavour

### ISSUE THREAD

**Issue by cewbdex** [lineageos4microg/docker-lineage-cicd#491]
Sorry if I open the issue at a wrong place. I had lineageos on my santoni, however I decided to give microg a try, it's a bit pain to setup, so I decided to switch up rom. After dirty reflash the camera was not working, so I wiped the data, but still nothing, so: I wiped in order cache, system, data, flashed stock lineage. Camera works. wiped like before, flashed microg flavour, but no camera working, not even flash in top bar.

**Comment by petefoth** [comment]
The only thing I can suggest is that you ***format*** data partition rather than wiping. As stated [in the README](https://github.com/lineageos4microg/docker-lineage-cicd#clean-and-dirty-flashing), dirty flashing is not guaranteed to work. 

If formatting data doesn't help, then, as also stated in [the README](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support)
> we recommend that you ask for help in [the XDA Forum thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/) or in device specific [XDA forum threads](https://forum.xda-developers.com/). The LineageOS for MicroG forum thread is not maintained by us, but there are many knowledgeable contributors there, who build and run the LineageOS for MicroG ROM on a wide variety of devices.

**Comment by cewbdex** [comment]
Sorry, it was a format, not wipe, I did not know there is a difference. I don't have an XDA account, but that is the only way I guess?

**Comment by petefoth** [comment]
> I don't have an XDA account, but that is the only way I guess?

I'm afraid so - yes.
