### ISSUE TITLE
Asks for GitHub credentials

### ISSUE THREAD

**Issue by mathbr** [lineageos4microg/docker-lineage-cicd#51]
Since the last few builds I noticed that running a build with this image suddenly asks for my GitHub username and password:

```
Set cache size limit to 50.0 GB
>> [Sun Aug 25 12:38:25 UTC 2019] Branch:  cm-14.1
>> [Sun Aug 25 12:38:25 UTC 2019] Devices: suzuran,
>> [Sun Aug 25 12:38:27 UTC 2019] (Re)initializing branch repository
>> [Sun Aug 25 12:38:29 UTC 2019] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Sun Aug 25 12:38:29 UTC 2019] Syncing branch repository
Username for 'https://github.com': mathbr
Password for 'https://mathbr@github.com': >> [Sun Aug 25 12:43:19 UTC 2019] Setting "UNOFFICIAL" as release type
>> [Sun Aug 25 12:43:19 UTC 2019] Adding OTA URL overlay (for custom URL )
>> [Sun Aug 25 12:43:19 UTC 2019] Using OpenJDK 8
>> [Sun Aug 25 12:43:20 UTC 2019] Preparing build environment
>> [Sun Aug 25 12:43:21 UTC 2019] Starting build for suzuran, cm-14.1 branch
...
```

Here I cancelled on the password prompt since I obviously don't want to input my GitHub credentials without knowing why.

Do you have an idea why this happens? This is rather new since I did quite a few builds without this just fine before.

Would it be possible to use SSH instead of HTTPS? Then I could use an SSH agent to give access.

I also noticed that the security level of my device is not bumped after flashing the newest ZIPs so I assume some source code has not been updated.

**Comment by fkoester** [comment]
Having the same problem here as well

**Comment by fkoester** [comment]
I figured it out. I tried to build the `cm-14.1` branch and the XML file that in this case gets downloaded is https://github.com/TheMuppets/manifests/blob/cm-14.1/muppets.xml.

In there is the following line that points to the repo for xiaomi proprietary files: 
```xml
<project name="TheMuppets/proprietary_vendor_xiaomi" path="vendor/xiaomi"/>
```

But this repository apparently was taken down due to a DCMA request https://github.com/TheMuppets/proprietary_vendor_xiaomi.

When access to a repo is denied GitHub requests authentication from the client, hence the ask for credentials. Entering any will obviously not help, though.

I therefore disabled the automatic handling of proprietary files, copied the XML file from the URL above _without the xiaomi line_ to `local_manifests` and the sync and build worked fine after that.

There is also a PR for the manifests file: https://github.com/TheMuppets/manifests/pull/10

**Comment by mathbr** [comment]
@fkoester Thanks for the hint. Can you add more details what exactly you did? (What files to download, volumes to mount, environment variables to set, additional commands to execute, ...)

**Comment by fkoester** [comment]
1. Download https://github.com/TheMuppets/manifests/blob/cm-14.1/muppets.xml and put it in a folder, for instance `./local_manifests`
2. Edit the downloaded file and delete the entire line with `xiaomi` in it
3. Run the docker image `lineageos4microg/docker-lineage-cicd` with the following options:
`-v "./local_manifests:/srv/local_manifests" -e "INCLUDE_PROPRIETARY=false"`

**Comment by mathbr** [comment]
@fkoester Works like a charm, thanks a lot!
