### ISSUE TITLE
'.img' files and build logs are mis-dated

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#562]
These files are named using `$builddate`, [which is set to the date the `repo sync` is performed](https://github.com/lineageos4microg/docker-lineage-cicd/blob/f0b871fe60df4c47ac77bd9c1ff7ee61e0bb3f18/src/build.sh#L198C1-L202C1) (which is the date the bulid run is started, not the date each device was built. So `.log`and `.img` files for the January 2024 build of e.g. `nio` are named `lineage-20.0-20240101-microG-nio...` rather than `lineage-20.0-20240111-microG-nio...`

The solution is to reset `$builddate` [when the build for each device is started](https://github.com/lineageos4microg/docker-lineage-cicd/blob/f0b871fe60df4c47ac77bd9c1ff7ee61e0bb3f18/src/build.sh#L319C1-L322C1)

**Comment by ArchangeGabriel** [comment]
On other hand, I find it more interesting to know the date of the sync than of the build. Because if I want to know whether a given upstream commit is in, that’s more relevant (of course for myself I would know that anything past the 1st of the month is not included, but that might not be the case for everyone). In particular, I guess some people would expect that a build date late in the month has the security fixes of the month (which are not available on the 1st).

**Comment by petefoth** [comment]
With regular build runs the date of the sync will always be the first day of the month. The name of the ROM zip file was already set to the date the device build starts. this change only ensures that the `.img`  files (and their `.sha256sum` files) have the same date. At the moment they do not, and that is confusing.

**Comment by petefoth** [comment]
For the ROMs built today, all files have the correct date `20240202` :)
