### ISSUE TITLE
Ignore a folder

### ISSUE THREAD

**Issue by DonPicciotto** [lineageos4microg/docker-lineage-cicd#584]
Hi, sorry for my noobish question, but I really don't have any experience as a developer of any kind. I usually build LOS for officially supported device with this image and everything works great, but since 18.1 will be deprecated I will need to build a Redmi Note 5 (whyred) LOS20 with external sources. I followed the example for a6000 and used this manifest https://github.com/Whyred-Dynamic-Development/local_manifest/blob/lineage-20/bouquet.xml but the build fail with 
```
FAILED:
In file included from out/soong/installs-lineage_whyred.mk:183176:
In file included from out/soong/Android-lineage_whyred.mk:629540:
In file included from build/make/core/soong_cc_rust_prebuilt.mk:54:
build/make/core/base_rules.mk:338: error: hardware/qcom-caf/msm8998/display: MODULE.TARGET.HEADER_LIBRARIES.display_headers already defined by hardware/qcom-caf/bouquet/display.
```
I notice there are custom sources in the manifest that would conflict with hardware/qcom-caf/msm8998, so I was wondering if there would be a way to ignore that folder when build for whyred. I tried just moving the folder out but obviously when Lineage repo synced again at the start of the build process the folder came back.
Thanks in advance for any help and sorry if I couldn't explain myself correctly!

**Comment by petefoth** [comment]
> I notice there are custom sources in the manifest that would conflict with hardware/qcom-caf/msm8998, so I was wondering if there would be a way to ignore that folder when build for whyred.

You could try using a `<remove-project>` line in your manifest: - see [here](https://gerrit.googlesource.com/git-repo/+/master/docs/manifest-format.md#element-remove_project) for the reference and e.g. [here](https://github.com/Professor-Berni/local_manifests/blob/lineage-21.0/removes.xml) for examples of how to use.

Good luck

**Comment by petefoth** [comment]
Well I'm a bit out of my depth - I've never tried porting device from one Android version to a higher one.

The first thing I would try would be to remove the `hardware/qcom-caf/bouquet...` lines from the manifest, and use the ones from the LineageOS repos instead.

Also, I note that the `lineage-20.` is the default branch in  the [LineageOS `android_device_xiaomi_whyred` repo](https://github.com/LineageOS/android_device_xiaomi_whyred/). Why not try building using that - and maybe other LineageOS repos instead of the `Whyred-Dynamic-Development` repos?

Finally, I would say that Docker isn't a very friendly tool when you're doing experiments like this: the master image will always do all the operations (see note below) - `repo init`, `repo sync`, `mka` which can take a lot of time. I would be tempted to start out by making a 'normal' (i.e. non-microG) LineageOS 20.0 build, using the command line method described in [the LineageOS build instructions](https://wiki.lineageos.org/devices/whyred/build/), picking up vendor blobs from https://github.com/TheMuppets/proprietary_vendor_xiaomi_whyred. When you've got that building / working. then you can make the microG build using docker. 


> and if this could help, the developer told me to do this [RisingTechOSS/android_vendor_rising@793eb71](https://github.com/RisingTechOSS/android_vendor_rising/commit/793eb718fcb57a628ed3f9bf960d3f9be29afe20) but I'm not sure how I should apply it on a docker image

You could apply a patch to the file, in a  userscript: either`before.sh` (called once per `docker run`, after the call to `repo sync`), or `pre-build.sh` (called for each device, after call to `breakfast`, before call to `mka`). Iwould probably go with `before.sh`. The file needs to be in the `/srv/userscripts` directory, with `execute` permission, before calling docker.

I hope all that is useful, but it's probably a bit off-topic for this project :). Good luck again


Note: the [`experimental` branch in this repo](https://github.com/lineageos4microg/docker-lineage-cicd/tree/experimental) and the corresponding docker image (`docker pull lineageos4microg/docker-lineage-cicd:experimental`) have a more flexible approach, allowing some longer running operations to be 'switched off'

**Comment by petefoth** [comment]
> Well I'm a bit out of my depth - I've never tried porting device from one Android version to a higher one.
> 
> The first thing I would try would be to remove the `hardware/qcom-caf/bouquet...` lines from the manifest, and use the ones from the LineageOS repos instead.
> 
> Also, I note that the `lineage-20.` is the default branch in the [LineageOS `android_device_xiaomi_whyred` repo](https://github.com/LineageOS/android_device_xiaomi_whyred/). Why not try building using that - and maybe other LineageOS repos instead of the `Whyred-Dynamic-Development` repos?
> 
> Finally, I would say that Docker isn't a very friendly tool when you're doing experiments like this: the master image will always do all the operations (see note below) - `repo init`, `repo sync`, `mka` which can take a lot of time. I would be tempted to start out by making a 'normal' (i.e. non-microG) LineageOS 20.0 build, using the command line method described in [the LineageOS build instructions](https://wiki.lineageos.org/devices/whyred/build/), picking up vendor blobs from https://github.com/TheMuppets/proprietary_vendor_xiaomi_whyred. When you've got that building / working. then you can make the microG build using docker.
> 
> > and if this could help, the developer told me to do this [RisingTechOSS/android_vendor_rising@793eb71](https://github.com/RisingTechOSS/android_vendor_rising/commit/793eb718fcb57a628ed3f9bf960d3f9be29afe20) but I'm not sure how I should apply it on a docker image
> 
> You could apply a patch to the file, in a userscript: either`before.sh` (called once per `docker run`, after the call to `repo sync`), or `pre-build.sh` (called for each device, after call to `breakfast`, before call to `mka`). Iwould probably go with `before.sh`. The file needs to be in the `/srv/userscripts` directory, with `execute` permission, before calling docker.
> 
> I hope all that is useful, but it's probably a bit off-topic for this project :). Good luck again
> 
> Note: the [`experimental` branch in this repo](https://github.com/lineageos4microg/docker-lineage-cicd/tree/experimental) and the corresponding docker image (`docker pull lineageos4microg/docker-lineage-cicd:experimental`) have a more flexible approach, allowing some longer running operations to be 'switched off'

Note that the `experimental` branch has now been merged to `master`, so the switchable operations functionality is now available in the `master` / `latest` docker image

Closing this issue, since it is 'off-topic` for this issue tracker
