### ISSUE TITLE
Any chance for gmscompat support?

### ISSUE THREAD

**Issue by marvin1099** [lineageos4microg/docker-lineage-cicd#598]
As many of you may know lineageos isn't compatible with gmscompat.
gmscompat is the grapheneos compatibility layer of google apps in a sandbox.
I quite shure that it would be out of the scope of lineageos itself, also i dont think they would even want to do it, based on the reason that they didn't want signature spoofing.
That might not say a lot but this project is way closer to supporting gmscompat.
So I was hoping that it may be worth to support it or maby have a addon for it that you add in recovery.
To be clear Im not asking for the grapheneos compat apps to be installed out of the box, just that there would be compatibility for them, so that they can be installed with sideloading, as a module or something like that.
This souldn't affect anyone that dosn't want full gms apps but gives those that want it a better a way of using them.
This request i hopefully worth considering.
If there is a way to patch something like this in when building, please say so.
I realy like to have a gms option that isn't that invasive.

**Comment by petefoth** [comment]
It's an interesting idea, but I think it is definitely out of scope for this project: we make LineageOS with microG integrated, to ***replace*** the Google APIs and libraries. From what I've read about `gmscompat`(see [1], [2] & [3]) it allows running the Google apps that provide those APIs in a sandbox. Seems to me that the two things can't coexist: EITHER you use microG OR you use `gmscompat`.

It would definitely be ***possible*** to fork this project, and adapt the docker image so that it includes  `gmscompat` ***instead*** of microG, but that's not going to happen as part of this project - sorry!

[1] https://xdaforums.com/t/guide-grapheneoss-sandboxed-play-services-in-your-rom.4340557/
[2] https://www.reddit.com/r/LineageOS/comments/pmd6p0/graphene_os_sandboxed_play_services/
[3] https://github.com/sn-00-x/lineage-gmscompat/tree/master

**Comment by BurhanBudak** [comment]
> It's an interesting idea, but I think it is definitely out of scope for this project: we make LineageOS with microG integrated, to _**replace**_ the Google APIs and libraries. From what I've read about `gmscompat`(see [1], [2] & [3]) it allows running the Google apps that provide those APIs in a sandbox. Seems to me that the two things can't coexist: EITHER you use microG OR you use `gmscompat`.
> 
> It would definitely be _**possible**_ to fork this project, and adapt the docker image so that it includes `gmscompat` _**instead**_ of microG (see [3]), but that's not going to happen as part of this project - sorry!
> 
> [1] https://xdaforums.com/t/guide-grapheneoss-sandboxed-play-services-in-your-rom.4340557/ [2] https://www.reddit.com/r/LineageOS/comments/pmd6p0/graphene_os_sandboxed_play_services/ [3] https://github.com/sn-00-x/lineage-gmscompat/tree/master

Both have their advantages but gmscompat has more compatibility to passing any Play Integrity. GOS can pass Play Integrity but  GOS devs dont allow any ROOT so Magisk, aPatch, KernelSU is out of the question. While RCS can work with microG if you backup a apk from a regular Gapps phone, gmscompact is Gapps in a sandbox.

**Comment by petefoth** [comment]
> Both have their advantages but gmscompat has more compatibility to passing any Play Integrity.

So maybe there is a market for a LineageOS for GMSCompat custom ROM. Good luck with that project, but ***this*** is the LineageOS ***for microG*** project, and that isn't about to change
