### ISSUE TITLE
LineageOS now supports signature spoofing by microG

### ISSUE THREAD

**Issue by bananer** [lineageos4microg/docker-lineage-cicd#634]
https://review.lineageos.org/q/topic:microg-eval

https://www.reddit.com/r/LineageOS/comments/1b11zex/los_has_added_internal_microg_support/

Does that make lineageos4microg obsolete?

**Comment by petefoth** [comment]
Hi Philip

> Does that make lineageos4microg obsolete?

Not in my opinion. They 'support' it only in so far as it is no longer necessary to patch the LOS ROM to install microG. But they don't make builds with microG already installed, and with F-Droid installed and pre-configured to keep microg updated. And as far as I can see, they won't ever do that. 

They also still refuse to provide any support for builds with microG in their irc/discord and reddit support channels, because it's 'unofficial`. 

It does mean that we will no longer have to implement and maintain our own patches for future android versions, at least for the builds we make. But their support only allows `restricted` spoofing, only for `GmsCore`, and only in `userdebug` builds. So if we wanted to continue to support ROM builders who want either 'full' signature spoofing, or who want any form of spoofing in e.g. `user` builds (see #614) , we **_would_** need to  make our own patches for future android versions. I'm not sure whether either of these are 'real' use cases, but we don't need to make that decision until we start working on Android 15.

Note that the latest builds (April & May) are built using the upstream patches rather than ours, i.e. the `SIGNATURE_SPOOFING`environment variable is set to 'no` in our `docker run` command.

**Comment by petefoth** [comment]
Also, only supported for LOS 18.1 and later versions. Still need our patches to build 17.1 and earlier versions

**Comment by bananer** [comment]
Cool, thanks for your continued engagement!
