### ISSUE TITLE
September 21.0 builds failing

### ISSUE THREAD

**Issue by st3rox** [lineageos4microg/docker-lineage-cicd#677]
Looks like all the builds are failing this month's run

**Comment by petefoth** [comment]
Yes. I will try to work out what is going on when I have some time

**Comment by petefoth** [comment]
Looks like it's only the 21.0 builds that are failing. 20.0 builds seem to be progression past the point at which the 21. builds are failing. Issue title edited

**Comment by petefoth** [comment]
The 21.0 builds  are all failing at the `analyzing Android.bp files and generating ninja file` stage: When building` a52q` the reported error is `error: vendor/fairphone/FP5/Android.bp:5:1: module "soong_namespace": namespace device/fairphone/FP5 does not exist;` (full error message at https://pastebin.com/AnENbKrk)

Official builds (like [this one for `akari`](https://buildkite.com/lineageos/android/builds/69532#0191a4a1-ea6e-4251-a8bc-4f46aaf075d3)) were failing with this error a few of days ago, but I'  not sure what was done to fix the official builds, which are now succeeding. 

I've asked in the official [`lineageos-dev` Disord / irc](https://discord.com/channels/628008280605589549/653821680430481418) would be very grateful if anyone here has any ideas about what we need to do to fix this.

**Comment by petefoth** [comment]
So, I think I now understand a bit more about what is going on. Upstream LOS fixed these build errors in these commits in their `build.sh`
- https://github.com/lineageos-infra/build-config/commit/aef729c0db717ac32f72f10013a2f6fd07ce882b
- https://github.com/lineageos-infra/build-config/commit/275f95866bb3bf5396755e314fe90f9bb534165b

Not straightforward to apply the changes to our `build.sh` because 
- theirs builds only for ***a single device*** so each step `repo init`, `repo sync`, `breakfast`, `mka` etc. is preformed only once
- ours builds for ***several devices***, and some steps - `repo init`, `repo sync`- are called only once, while others `breakfast`, `mka` - are called once per device.

So we may need to restructure our `build.sh` a bit. I'm going to take some time to think about the best way of doing that before I start changing any code. While doing that, I will also think about moving our `build.sh` closer to theirs. (I suspect they started from the same place, but have developed differently during the years when upstream would not talk to or about microG.) That will make it easier to keep instep with any changes that need to be made because of e.g. changes in AOSP. 

With luck, we **_may_** have something that is able to make 21.0 builds by the time the 20.0 builds currently in progress have finished

Thanks for you patience

**Comment by petefoth** [comment]
A possible fix is available in the [`pf-restructure-build` branch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/pf-restructure-build)

I have been running a test, by trying a build for `akari` (on a very slow machine). The build is not yet complete, but it has got passed the point in the build where builds have been failing

> `[100% 1167/1167] analyzing Android.bp files and generating ninja file at out/soong/build.lineage_akari.ninja`

If anyone else want to try it, the image is available from Docker Hub

`docker pull lineageos4microg/docker-lineage-cicd:pf-restructure-build`

Any feedback is very welcome. 

The 20.0 builds are close to complete. I will kick off a run of 21.0 builds using the 'fixed' image, unless anyone can find any problems with it

**Comment by johnjacob10** [comment]
Unfortunately, this PR is not working for me. I tried building both the devices I own: Essential PH-1 (mata) and Google Pixel 5 (redfin).

The buiild command is:
```  
    if [[ "${PRODUCT}" == "mata" ]]; then
        /usr/bin/docker run \
            -e BRANCH_NAME="${BRANCH}" \
            -e DEVICE_LIST="${PRODUCT}"\
            -e RELEASE_TYPE="${BUILD_TYPE}" \
            -e USER_NAME="<redacted>" \
            -e USER_MAIL="<redacted>" \
            -e OTA_URL="<redacted>" \
            -e CCACHE_SIZE="100G" \
            -e SIGN_BUILDS="true" \
            -e SIGNATURE_SPOOFING="restricted" \
            -e BUILD_OVERLAY="false" \
            -e ZIP_SUBDIR="false" \
            -e LOGS_SUBDIR="false" \
            -e CUSTOM_PACKAGES="${1}" \
            -e INCLUDE_PROPRIETARY="true" \
            -e KEYS_SUBJECT="<redacted>" \
            -e ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx24G" \
            -e CLEAN_AFTER_BUILD="true" \
            -e TOP="/srv/src/${BRANCH}" \
            -e ANDROID_BUILD_BANNER="LineageOS 21.0 mata micro4G" \
            -e MKBOOTIMG="/srv/userscripts/mkbootimg.lineage" \
            -e BOARD_CUSTOM_MKBOOTIMG="/srv/userscripts/mkbootimg.lineage" \
            --name="${ROM}" \
            -v "${BASE_PATH}/source":/srv/src \
            -v "${BASE_PATH}/builds":/srv/zips \
            -v "${BASE_PATH}/logs":/srv/logs \
            -v "${BASE_PATH}/cache/${ROM}":/srv/ccache \
            -v "${BASE_PATH}/keys/${ROM}/${PRODUCT}":/srv/keys \
            -v "${BASE_PATH}/manifests/${ROM}":/srv/local_manifests \
            -v "${BASE_PATH}/scripts":/srv/userscripts \
            "${DOCKER_TAG}"
    elif [[ "${PRODUCT}" == "redfin" ]]; then
        /usr/bin/docker run \
            -e BRANCH_NAME="${BRANCH}" \
            -e DEVICE_LIST="${PRODUCT}"\
            -e RELEASE_TYPE="${BUILD_TYPE}" \
            -e USER_NAME="redacted" \
            -e USER_MAIL="redacted" \
            -e OTA_URL="redacted" \
            -e CCACHE_SIZE="100G" \
            -e SIGN_BUILDS="true" \
            -e SIGNATURE_SPOOFING="restricted" \
            -e BUILD_OVERLAY="false" \
            -e ZIP_SUBDIR="false" \
            -e LOGS_SUBDIR="false" \
            -e CUSTOM_PACKAGES="${1}" \
            -e INCLUDE_PROPRIETARY="true" \
            -e KEYS_SUBJECT="redacted" \
            -e ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx24G" \
            -e CLEAN_AFTER_BUILD="true" \
            -e TOP="/srv/src/${BRANCH}" \
            -e ANDROID_BUILD_BANNER="LineageOS 21.0 redfin micro5G" \
            --name="${ROM}" \
            -v "${BASE_PATH}/source":/srv/src \
            -v "${BASE_PATH}/builds":/srv/zips \
            -v "${BASE_PATH}/logs":/srv/logs \
            -v "${BASE_PATH}/cache/${ROM}":/srv/ccache \
            -v "${BASE_PATH}/keys/${ROM}/${PRODUCT}":/srv/keys \
            -v "${BASE_PATH}/manifests/${ROM}":/srv/local_manifests \
            -v "${BASE_PATH}/scripts":/srv/userscripts \
            "${DOCKER_TAG}"
    else
        _log "Fatal: Unknown product ${PRODUCT}."
        exit 1
    fi
```

Where:
```
# Args - ${1} : Android code name of product to build.
setup_env() {
    case "${1}" in
        "mata")
            _log "Info: Building for Essential PH-1 (mata)."
            export PRODUCT="mata"
            export BUILD_TYPE="micro4G"
        ;;
        "redfin")
            _log "Info: Building for Google Pixel 5 (redfin)."
            export PRODUCT="redfin"
            export BUILD_TYPE="micro5G"
        ;;
        *)
            if [[ -z "${1}" ]];
            then
                _log "Fatal: Product is not specified, abandoning build."
            else
                _log "Fatal: Invalid product \"${1}\" specified."
            fi
            exit 1
        ;;
    esac
    export ROM="lineage"
    export TREE="LINEAGE_21_0"
    export BRANCH="lineage-21.0"
    export DOCKER_TAG="username/lineage"
    export IMAGE_PREFIX="${BRANCH}"
    export IMAGE_POSTFIX="${BUILD_TYPE}-${PRODUCT}"
    export BASE_PATH="/var/local/android"
    export BUILD_PATH="${BASE_PATH}/builds"
    export DOCKER_PATH="${BASE_PATH}/docker/${ROM}"
    export LOG_PATH="${BASE_PATH}/logs"
    export SOURCE_PATH="${BASE_PATH}/source/${TREE}"
    export BUILD_DATE="$(/usr/bin/date +%Y%m%d)"
    export IMAGE_NAME="${IMAGE_PREFIX}-${BUILD_DATE}-${IMAGE_POSTFIX}"
}
```
I've attached the log files for both devices. I use a build script to do the build, and I can attach that too, if it would help - let me know.

I haven't really had time to debug this myself yet, but if you can't see anything obvious from the logs, I will try debugging further.
[lineage-21.0-20240907-micro4G-mata.zip_FAILED.log](https://github.com/user-attachments/files/16919196/lineage-21.0-20240907-micro4G-mata.zip_FAILED.log)
[lineage-21.0-20240907-micro5G-redfin.zip_FAILED.log](https://github.com/user-attachments/files/16919197/lineage-21.0-20240907-micro5G-redfin.zip_FAILED.log)

**Comment by gwstorm** [comment]
> A possible fix is now available in the [`pf-restructure-build` branch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/pf-restructure-build)

Just wanted to comment that `:latest` was failing for me as mentioned and [`pf-restructure-build` branch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/pf-restructure-build) indeed worked for lemonadep.

Error under `:latest` seemed to stem from `build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_lemonadep".`

**Comment by petefoth** [comment]
> Error under `:latest` seemed to stem from `build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "lineage_lemonadep".`

That's not the root cause, which will have happened earlier in the `breakfast` process.

**Comment by gwstorm** [comment]
Fair enough. I've a pretty near 0% success rate on reading these logs. It's a short log so I'll just attach it in case it's of any value as to why this version worked and the other didn't.

Anyway, thanks for keeping it all going!
 
[lineage-21.0-20240920-UNOFFICIAL-lemonadep.log](https://github.com/user-attachments/files/17080750/lineage-21.0-20240920-UNOFFICIAL-lemonadep.log)

**Comment by petefoth** [comment]
So some hints about interpreting the log file 
1. I was wrong, the error you quoted happens near the start and is quite normal because, at that point, the `lineage_lemonadep.mk` makefile doesn't exit in the source tree. So, after the full `repo sync`, the build hunts round  in the places it knows about to find that makefile, and any other dependencies it can detect. That's what happening in lines 10-44. By line 44 it has found all the dependencies it has identified, and the build can start
2. Everything goes fine for the next 1200 or so lines then...
3. ... the real error occurs at lines 1261-1265
> [100% 1167/1167] analyzing Android.bp files and generating ninja file at out/soong/build.lineage_lemonadep.ninja
> FAILED: out/soong/build.lineage_lemonadep.ninja
> cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_lemonadep.variables -o out/soong/build.lineage_lemonadep.ninja --globListDir lineage_lemonadep --globFile out/soong/globs-lineage_lemonadep.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_lemonadep.build Android.bp
> error: vendor/google/akita/Android.bp:5:1: module "soong_namespace": namespace device/google/akita does not exist; 

This is the same error that was occurring in all our builds, and in the upstream LOS builds, until they implemented the fix as mentioned above
> . Upstream LOS fixed these build errors in these commits in their `build.sh`
> * [lineageos-infra/build-config@aef729c](https://github.com/lineageos-infra/build-config/commit/aef729c0db717ac32f72f10013a2f6fd07ce882b)
> * [lineageos-infra/build-config@275f958](https://github.com/lineageos-infra/build-config/commit/275f95866bb3bf5396755e314fe90f9bb534165b)
> 
> Also this commit in [`TheMuppets/manifests` repo](https://github.com/TheMuppets/manifests)
> * [TheMuppets/manifests@007c9d6](https://github.com/TheMuppets/manifests/commit/007c9d6f19444b70aa588fa0fd1fc27e2b4d491a)

As a general rule, searching the log file for the string `FAILED:` will get you to the point where the real error occurred, which may be quite a long way before the end, because the build won't stop until all the processes that are running in parallel with the failed process complete. Some of the tasks in those processes - e.g. building a kernel image - may run on for a long time and write a lot more to the log file before the build stops.
